from pathlib import Path

from app.core.config import get_settings
from app.models.db import Database, LexiconEntry, Token
from app.services.analytical_codes import parse_analytical_code
from app.services.pronunciation import transliteration_to_zhuyin_like
from app.services.strongs import normalize_strongs

SAMPLE_TOKENS = [
    {
        "verse_ref": "Gen.1.1",
        "token_order": 1,
        "surface_form": "בְּרֵאשִׁית",
        "normalized_form": "ראשית",
        "lemma": "רֵאשִׁית",
        "strongs_primary": "H7225",
        "strongs_secondary": None,
        "analytical_code_raw": "N-NOM-SG-FEM",
        "part_of_speech": "noun",
        "morphology_features": {"case": "nominative", "number": "singular", "gender": "feminine"},
        "literal_gloss_en": "beginning",
        "translation_note_zh": "時間起點，導入創造敘事",
        "recovery_alignment_note": "恢復本常對應『起初』",
        "pronunciation_transliteration": "bereshit",
        "source_layer": "OSHB|WLC",
        "verse_usage": "作整段時序引言",
        "grammar_explanation": "名詞片語作句首框架",
        "is_ot_quote": False,
    },
    {
        "verse_ref": "Gen.1.1",
        "token_order": 2,
        "surface_form": "אֱלֹהִים",
        "normalized_form": "אלהים",
        "lemma": "אֱלֹהִים",
        "strongs_primary": "H430",
        "strongs_secondary": None,
        "analytical_code_raw": "N-NOM-PL-MASC",
        "part_of_speech": "noun",
        "morphology_features": {"case": "nominative", "number": "plural-form", "gender": "masculine"},
        "literal_gloss_en": "God",
        "translation_note_zh": "複數形態但在神名語境常作單數意義",
        "recovery_alignment_note": "恢復本多譯『神』",
        "pronunciation_transliteration": "elohim",
        "source_layer": "OSHB|WLC",
        "verse_usage": "作主詞",
        "grammar_explanation": "形態複數、語義單一神稱",
        "is_ot_quote": False,
    },
    {
        "verse_ref": "Exod.3.14",
        "token_order": 1,
        "surface_form": "אֶהְיֶה",
        "normalized_form": "היה",
        "lemma": "היה",
        "strongs_primary": "H1961",
        "strongs_secondary": None,
        "analytical_code_raw": "V-IMPF-1-SG-IND-ACT",
        "part_of_speech": "verb",
        "morphology_features": {"tense": "imperfect", "person": "1", "number": "singular", "voice": "active"},
        "literal_gloss_en": "I am / I will be",
        "translation_note_zh": "可含存有與將成就雙重語感",
        "recovery_alignment_note": "恢復本常作『我是』",
        "pronunciation_transliteration": "ehyeh",
        "source_layer": "OSHB|WLC",
        "verse_usage": "神自我啟示",
        "grammar_explanation": "未完成式呈現持續/將然語氣",
        "is_ot_quote": False,
    },
    {
        "verse_ref": "John.1.1",
        "token_order": 1,
        "surface_form": "λόγος",
        "normalized_form": "λογος",
        "lemma": "λόγος",
        "strongs_primary": "G3056",
        "strongs_secondary": None,
        "analytical_code_raw": "N-NOM-SG-MASC",
        "part_of_speech": "noun",
        "morphology_features": {"case": "nominative", "number": "singular", "gender": "masculine"},
        "literal_gloss_en": "word",
        "translation_note_zh": "可表達話語、發表、神聖表達",
        "recovery_alignment_note": "恢復本多譯『話』",
        "pronunciation_transliteration": "logos",
        "source_layer": "SBLGNT|MorphGNT",
        "verse_usage": "作主詞核心名詞",
        "grammar_explanation": "定義性名詞與上下文神學連結",
        "is_ot_quote": False,
    },
    {
        "verse_ref": "John.1.1",
        "token_order": 2,
        "surface_form": "θεός",
        "normalized_form": "θεος",
        "lemma": "θεός",
        "strongs_primary": "G2316",
        "strongs_secondary": None,
        "analytical_code_raw": "N-NOM-SG-MASC",
        "part_of_speech": "noun",
        "morphology_features": {"case": "nominative", "number": "singular", "gender": "masculine"},
        "literal_gloss_en": "God",
        "translation_note_zh": "無冠詞位置需結合語序判定性質",
        "recovery_alignment_note": "恢復本譯為『神』",
        "pronunciation_transliteration": "theos",
        "source_layer": "SBLGNT|MorphGNT",
        "verse_usage": "神性陳述",
        "grammar_explanation": "名詞述語位置，需避免簡化成不定冠詞邏輯",
        "is_ot_quote": False,
    },
    {
        "verse_ref": "John.1.14",
        "token_order": 1,
        "surface_form": "σὰρξ",
        "normalized_form": "σαρξ",
        "lemma": "σάρξ",
        "strongs_primary": "G4561",
        "strongs_secondary": None,
        "analytical_code_raw": "N-NOM-SG-FEM",
        "part_of_speech": "noun",
        "morphology_features": {"case": "nominative", "number": "singular", "gender": "feminine"},
        "literal_gloss_en": "flesh",
        "translation_note_zh": "指成為具體人性存在",
        "recovery_alignment_note": "恢復本譯『成了肉體』",
        "pronunciation_transliteration": "sarx",
        "source_layer": "SBLGNT|MorphGNT",
        "verse_usage": "道成肉身主題",
        "grammar_explanation": "名詞作補語，描述狀態轉換",
        "is_ot_quote": False,
    },
    {
        "verse_ref": "Rom.8.2",
        "token_order": 1,
        "surface_form": "πνεῦμα",
        "normalized_form": "πνευμα",
        "lemma": "πνεῦμα",
        "strongs_primary": "G4151",
        "strongs_secondary": None,
        "analytical_code_raw": "N-NOM-SG-NEUT",
        "part_of_speech": "noun",
        "morphology_features": {"case": "nominative", "number": "singular", "gender": "neuter"},
        "literal_gloss_en": "spirit",
        "translation_note_zh": "可指靈、氣息；需依上下文判定",
        "recovery_alignment_note": "恢復本常作『那靈』",
        "pronunciation_transliteration": "pneuma",
        "source_layer": "SBLGNT|MorphGNT",
        "verse_usage": "生命律主題",
        "grammar_explanation": "中性名詞常與神學術語綁定",
        "is_ot_quote": False,
    },
    {
        "verse_ref": "1Cor.15.45",
        "token_order": 1,
        "surface_form": "Ἀδάμ",
        "normalized_form": "αδαμ",
        "lemma": "Ἀδάμ",
        "strongs_primary": "G76",
        "strongs_secondary": "H121",
        "analytical_code_raw": "N-NOM-SG-MASC-X",
        "part_of_speech": "noun",
        "morphology_features": {"case": "nominative", "number": "singular", "gender": "masculine", "type": "hebrew-loan"},
        "literal_gloss_en": "Adam",
        "translation_note_zh": "希伯來借詞進入希臘文語境",
        "recovery_alignment_note": "恢復本『末後的亞當』語境需連於基督論",
        "pronunciation_transliteration": "adam",
        "source_layer": "SBLGNT|MorphGNT",
        "verse_usage": "類型對比（首先/末後）",
        "grammar_explanation": "借詞專有名詞可有次級編碼",
        "is_ot_quote": True,
    },
    {
        "verse_ref": "Rev.22.17",
        "token_order": 1,
        "surface_form": "ἔρχου",
        "normalized_form": "ερχομαι",
        "lemma": "ἔρχομαι",
        "strongs_primary": "G2064",
        "strongs_secondary": None,
        "analytical_code_raw": "V-PRES-IMP-2-SG-M/P",
        "part_of_speech": "verb",
        "morphology_features": {"tense": "present", "mood": "imperative", "person": "2", "number": "singular", "voice": "middle/passive"},
        "literal_gloss_en": "come!",
        "translation_note_zh": "命令語氣有呼求/邀請雙重效果",
        "recovery_alignment_note": "恢復本譯『來』",
        "pronunciation_transliteration": "erchou",
        "source_layer": "SBLGNT|MorphGNT",
        "verse_usage": "結語呼召",
        "grammar_explanation": "中被動合併類型以 M/P 標示",
        "is_ot_quote": False,
    },
    {
        "verse_ref": "Matt.24.35",
        "token_order": 1,
        "surface_form": "οὐ μὴ",
        "normalized_form": "ου μη",
        "lemma": "οὐ μή",
        "strongs_primary": "G3756",
        "strongs_secondary": "G3361",
        "analytical_code_raw": "ADV-NEG-DOUBLE",
        "part_of_speech": "adverb",
        "morphology_features": {"type": "double_negation"},
        "literal_gloss_en": "not not",
        "translation_note_zh": "慣用雙重否定，語義為強烈否定",
        "recovery_alignment_note": "恢復本通常以強烈否定句法呈現",
        "pronunciation_transliteration": "ou mē",
        "source_layer": "SBLGNT|MorphGNT",
        "verse_usage": "語氣強調",
        "grammar_explanation": "雙重否定不作數學抵消而作強調",
        "is_ot_quote": False,
    },
]

LEXICON = [
    ("H430", "אֱלֹהִים", "Hebrew", "elohim", "God, gods", "God"),
    ("H1961", "היה", "Hebrew", "ehyeh", "to be", "be"),
    ("H7225", "רֵאשִׁית", "Hebrew", "bereshit", "beginning", "beginning"),
    ("G3056", "λόγος", "Greek", "logos", "word, expression, reason", "word"),
    ("G2316", "θεός", "Greek", "theos", "God", "God"),
    ("G2064", "ἔρχομαι", "Greek", "erchomai", "to come", "come"),
    ("G3756", "οὐ", "Greek", "ou", "not", "not"),
    ("G3361", "μή", "Greek", "mē", "not (subjunctive/volitive)", "not"),
]


def main() -> None:
    settings = get_settings()
    Path(settings.sqlite_path).parent.mkdir(parents=True, exist_ok=True)
    db = Database(settings.sqlite_path)
    db.reset_all()

    with db.session_local() as session:
        for row in SAMPLE_TOKENS:
            lang = "Hebrew" if row["strongs_primary"].startswith("H") else "Greek"
            translit = row["pronunciation_transliteration"]
            session.add(
                Token(
                    osis=row["verse_ref"].split(".")[0],
                    verse_ref=row["verse_ref"],
                    token_order=row["token_order"],
                    surface_form=row["surface_form"],
                    normalized_form=row["normalized_form"],
                    lemma=row["lemma"],
                    strongs_primary=normalize_strongs(row["strongs_primary"]),
                    strongs_secondary=normalize_strongs(row["strongs_secondary"]) if row["strongs_secondary"] else None,
                    analytical_code_raw=row["analytical_code_raw"],
                    analytical_code_expanded=parse_analytical_code(row["analytical_code_raw"]).expanded,
                    part_of_speech=row["part_of_speech"],
                    morphology_features=row["morphology_features"],
                    literal_gloss_en=row["literal_gloss_en"],
                    translation_note_zh=row["translation_note_zh"],
                    recovery_alignment_note=row["recovery_alignment_note"],
                    pronunciation_transliteration=translit,
                    pronunciation_bopomofo=transliteration_to_zhuyin_like(translit, lang),
                    source_layer=row["source_layer"],
                    verse_usage=row["verse_usage"],
                    related_refs=["John.1.1", "Rom.8.2", "Rev.22.17"],
                    grammar_explanation=row["grammar_explanation"],
                    is_ot_quote=row["is_ot_quote"],
                )
            )

        for s, lemma, lang, tr, definition, gloss in LEXICON:
            sid = normalize_strongs(s)
            session.add(
                LexiconEntry(
                    strongs=sid,
                    normalized_strongs=sid,
                    lemma=lemma,
                    language=lang,
                    transliteration=tr,
                    pronunciation_bopomofo=transliteration_to_zhuyin_like(tr, lang),
                    short_definition=definition,
                    literal_gloss_en=gloss,
                    common_inflections=[tr, f"{tr}s"],
                    analytical_notes=["form-priority", "function-exception-possible"],
                )
            )

        session.commit()


if __name__ == "__main__":
    main()
